# Generated by Django 5.1 on 2024-08-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoas',
            old_name='nomme',
            new_name='nome',
        ),
    ]
